const SPORTS=[['walking','Walking'],['cycling','Rad fahren'],['swimming','Schwimmen'],['nordic','Nordic Walking'],['cross','Crosstrainer'],['ergo','Ergometer']];
const KEY='meinSportDataV1';let db=load(), view='home', current='walking';
function load(){try{return JSON.parse(localStorage.getItem(KEY))||fresh()}catch{return fresh()}}function fresh(){return{version:1,metrics:[],activities:[],favorites:[]}}function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function icon(k){return `<img class="sport-pictogram" src="./icons/sports/${k}.png" alt="" aria-hidden="true">`}
function nav(){return `<nav class="nav"><button onclick="go('home')">Start</button><button onclick="go('data')">Daten</button><button onclick="go('chart')">Diagramm</button><button onclick="go('settings')">Setup</button></nav>`}
function render(){let a=document.querySelector('#app');a.innerHTML=`<main class="shell">${view==='home'?home():view==='data'?dataPage():view==='sport'?sportPage():view==='chart'?chartPage():settings()}</main>${nav()}`;if(view==='chart')setTimeout(drawChart)}
function home(){return `<div class="hero"><h1>Mein<br>Sport</h1><p>Deine Aktivitäten. Deine Daten.</p></div><div class="grid">${SPORTS.map(s=>`<button class="sport" onclick="openSport('${s[0]}')">${icon(s[0])}<b>${s[1]}</b><span class="small">${db.activities.filter(a=>a.sport===s[0]).length} Einträge</span></button>`).join('')}</div>`}
function dataPage(){let arr=[...db.activities].sort((a,b)=>b.date.localeCompare(a.date));return `<div class="top"><div class="brand">Daten</div><button class="btn" onclick="go('sport')">+ Eintrag</button></div><div class="panel">${arr.length?arr.map(a=>`<div class="activity"><b>${SPORTS.find(s=>s[0]===a.sport)?.[1]}</b> · ${a.date}<div class="small">${Object.entries(a.values).map(([id,v])=>{let m=db.metrics.find(x=>x.id===id);return m?`${esc(m.name)}: ${esc(v)} ${esc(m.unit||'')}`:''}).filter(Boolean).join(' · ')}</div><button class="pill" onclick="delAct('${a.id}')">Löschen</button></div>`).join(''):'<div class="empty">Noch keine Aktivitäten.</div>'}</div>`}
function sportPage(){let sport=SPORTS.find(s=>s[0]===current)||SPORTS[0], ms=db.metrics.filter(m=>m.sports.includes(current));return `<div class="top"><div class="brand">${sport[1]}</div>${icon(current)}</div><form class="panel stack" onsubmit="addAct(event)"><h2>Neue Aktivität</h2><label>Datum<input name="date" type="date" value="${new Date().toISOString().slice(0,10)}" required></label>${ms.map(m=>`<label>${esc(m.name)}${m.unit?' ('+esc(m.unit)+')':''}<input name="m_${m.id}" type="${m.type==='number'?'number':'text'}" step="any"></label>`).join('')}${ms.length?'':'<p class="small">Für diese Sportart sind noch keine Datenfelder angelegt. Das geht unter Setup.</p>'}<button class="btn">Speichern</button></form>`}
function settings(){return `<div class="brand">Setup</div><section class="panel"><h2>Datenfelder</h2><form class="stack" onsubmit="addMetric(event)"><input name="name" placeholder="z. B. Strecke" required><input name="unit" placeholder="Einheit, z. B. km"><select name="type"><option value="number">Zahl</option><option value="text">Text</option></select><div class="checks">${SPORTS.map(s=>`<label class="check"><input type="checkbox" name="sports" value="${s[0]}">${s[1]}</label>`).join('')}</div><button class="btn">Datenfeld anlegen</button></form>${db.metrics.map(m=>`<div class="metric"><span><b>${esc(m.name)}</b> ${esc(m.unit||'')}<br><span class="small">${m.sports.map(k=>SPORTS.find(s=>s[0]===k)?.[1]).join(', ')}</span></span><button class="pill" onclick="delMetric('${m.id}')">×</button></div>`).join('')}</section><section class="panel"><h2>Sicherung</h2><div class="row"><button class="btn" onclick="exportData()">Alles exportieren</button><button class="btn alt" onclick="document.querySelector('#importFile').click()">Importieren</button></div><p class="small">Exportiert Datenfelder, Aktivitäten und Diagramm-Favoriten als JSON.</p></section>`}
function chartPage(){let numeric=db.metrics.filter(m=>m.type==='number');return `<div class="brand">Diagramm</div><section class="panel stack"><h2>Daten verschneiden</h2><div class="checks">${numeric.map(m=>`<label class="check"><input class="series" type="checkbox" value="${m.id}" onchange="drawChart()">${esc(m.name)}</label>`).join('')}</div><canvas id="chart" width="700" height="360"></canvas><div class="row"><input id="favName" placeholder="Name des Favoriten" style="flex:1"><button class="btn" onclick="saveFav()">Favorit speichern</button></div></section><section class="panel"><h2>Favoriten</h2>${db.favorites.map(f=>`<div class="metric"><button class="pill" onclick="loadFav('${f.id}')">${esc(f.name)}</button><button class="pill" onclick="delFav('${f.id}')">×</button></div>`).join('')||'<div class="small">Noch keine Favoriten.</div>'}</section>`}
function go(v){view=v;if(v==='sport'&&!current)current='walking';render()}function openSport(k){current=k;view='sport';render()}
function addMetric(e){e.preventDefault();let f=new FormData(e.target),sports=f.getAll('sports');if(!sports.length)return alert('Bitte mindestens eine Sportart wählen.');db.metrics.push({id:crypto.randomUUID(),name:f.get('name'),unit:f.get('unit'),type:f.get('type'),sports});save();render()}
function delMetric(id){if(!confirm('Datenfeld löschen? Bereits gespeicherte Werte bleiben im Export, werden aber nicht mehr angezeigt.'))return;db.metrics=db.metrics.filter(m=>m.id!==id);save();render()}
function addAct(e){e.preventDefault();let f=new FormData(e.target),values={};db.metrics.filter(m=>m.sports.includes(current)).forEach(m=>{let v=f.get('m_'+m.id);if(v!=='')values[m.id]=m.type==='number'?Number(v):v});db.activities.push({id:crypto.randomUUID(),sport:current,date:f.get('date'),values});save();view='data';render()}
function delAct(id){db.activities=db.activities.filter(a=>a.id!==id);save();render()}
function selected(){return [...document.querySelectorAll('.series:checked')].map(x=>x.value)}
function drawChart(){let c=document.querySelector('#chart');if(!c)return;let ctx=c.getContext('2d'),ids=selected();ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle='#bbb';ctx.beginPath();ctx.moveTo(50,20);ctx.lineTo(50,320);ctx.lineTo(680,320);ctx.stroke();let rows=db.activities.filter(a=>ids.some(id=>a.values[id]!==undefined)).sort((a,b)=>a.date.localeCompare(b.date));if(!ids.length||!rows.length){ctx.fillStyle='#666';ctx.font='18px Arial';ctx.fillText('Datenreihen auswählen',220,180);return}let vals=rows.flatMap(a=>ids.map(id=>Number(a.values[id])).filter(Number.isFinite)),min=Math.min(...vals),max=Math.max(...vals);if(min===max){min-=1;max+=1}let marks=['#111','#19a8d8','#6dcc73','#ff812b','#8a5bd6','#d43c74'];ids.forEach((id,j)=>{ctx.strokeStyle=marks[j%marks.length];ctx.lineWidth=4;ctx.beginPath();let started=false;rows.forEach((a,i)=>{let v=Number(a.values[id]);if(!Number.isFinite(v))return;let x=50+(rows.length===1?315:i*630/(rows.length-1)),y=320-(v-min)*280/(max-min);started?ctx.lineTo(x,y):(ctx.moveTo(x,y),started=true)});ctx.stroke();ctx.fillStyle=marks[j%marks.length];ctx.fillRect(55,25+j*22,14,4);ctx.fillStyle='#111';ctx.font='14px Arial';ctx.fillText(db.metrics.find(m=>m.id===id)?.name||'',75,32+j*22)});ctx.fillStyle='#555';ctx.font='12px Arial';ctx.fillText(rows[0].date,50,342);ctx.fillText(rows.at(-1).date,600,342)}
function saveFav(){let ids=selected(),name=document.querySelector('#favName').value.trim();if(!ids.length||!name)return alert('Bitte Datenreihen wählen und einen Namen eingeben.');db.favorites.push({id:crypto.randomUUID(),name,metricIds:ids});save();render()}
function loadFav(id){let f=db.favorites.find(x=>x.id===id);document.querySelectorAll('.series').forEach(x=>x.checked=f.metricIds.includes(x.value));drawChart()}function delFav(id){db.favorites=db.favorites.filter(f=>f.id!==id);save();render()}
function exportData(){let blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mein-sport-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
document.querySelector('#importFile').addEventListener('change',async e=>{let f=e.target.files[0];if(!f)return;try{let x=JSON.parse(await f.text());if(!x.metrics||!x.activities||!x.favorites)throw 0;if(confirm('Import ersetzt alle aktuellen Daten. Fortfahren?')){db=x;save();render()}}catch{alert('Ungültige Backup-Datei.')}e.target.value=''})
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
