const SPORTS=[['walking','Walking'],['cycling','Rad fahren'],['swimming','Schwimmen'],['nordic','Nordic Walking'],['cross','Crosstrainer'],['ergo','Ergometer']];
const KEY='meinSportDataV1';
const DEFAULTS=[
 ['duration','Dauer','min','number',['walking','cycling','swimming','nordic','cross','ergo']],
 ['distance','Distanz','km','number',['walking','cycling','swimming','nordic','cross','ergo']],
 ['heart','Ø Herzfrequenz','bpm','number',['walking','cycling','swimming','nordic','cross','ergo']],
 ['effort','Belastung','1–10','number',['walking','cycling','swimming','nordic','cross','ergo']],
 ['elevation','Höhenmeter','m','number',['walking','cycling','nordic']],
 ['steps','Schritte','','number',['walking','nordic']],
 ['lanes','Bahnen','','number',['swimming']],
 ['power','Ø Leistung','W','number',['cross','ergo']],
 ['calories','Kalorien','kcal','number',['cross','ergo']],
 ['notes','Notizen','','text',['walking','cycling','swimming','nordic','cross','ergo']]
];
let db=load(),view='home',current='walking',editing=null,deferredInstallPrompt=null;ensureDefaults();
function fresh(){return{version:2,metrics:[],activities:[],favorites:[]}}
function load(){try{let x=JSON.parse(localStorage.getItem(KEY));return x&&Array.isArray(x.activities)?x:fresh()}catch{return fresh()}}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function ensureDefaults(){db.metrics=db.metrics||[];db.activities=db.activities||[];db.favorites=db.favorites||[];for(const [id,name,unit,type,sports] of DEFAULTS)if(!db.metrics.some(m=>m.id===id))db.metrics.push({id,name,unit,type,sports:[...sports],standard:true});db.version=2;save()}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function icon(k){return `<img class="sport-pictogram" src="./icons/sports/${k}.png" alt="" aria-hidden="true">`}
function nav(){return `<nav class="nav"><button onclick="go('home')">Start</button><button onclick="go('data')">Daten</button><button onclick="go('chart')">Auswertung</button><button onclick="go('settings')">Setup</button></nav>`}
function render(){document.querySelector('#app').innerHTML=`<main class="shell">${view==='home'?home():view==='data'?dataPage():view==='sport'?sportPage():view==='chart'?chartPage():settings()}</main>${nav()}`;if(view==='chart')setTimeout(drawChart)}
function home(){return `<div class="hero"><h1>Mein<br>Sport</h1><p>Deine Aktivitäten. Deine Daten.</p><button id="installBtn" class="btn" onclick="installApp()">${isStandalone()?'App ist installiert':'App installieren'}</button></div><div class="grid">${SPORTS.map(s=>`<button class="sport" onclick="openSport('${s[0]}')">${icon(s[0])}<b>${s[1]}</b><span class="small">${db.activities.filter(a=>a.sport===s[0]).length} Einträge</span></button>`).join('')}</div>`}
function activitySummary(a){return Object.entries(a.values||{}).map(([id,v])=>{let m=db.metrics.find(x=>x.id===id);return m&&v!==''?`${esc(m.name)}: ${esc(v)} ${esc(m.unit||'')}`:''}).filter(Boolean).join(' · ')}
function dataPage(){let arr=[...db.activities].sort((a,b)=>b.date.localeCompare(a.date));return `<div class="top"><div class="brand">Daten</div><button class="btn" onclick="newEntry()">+ Eintrag</button></div><div class="panel">${arr.length?arr.map(a=>`<div class="activity"><b>${SPORTS.find(s=>s[0]===a.sport)?.[1]}</b> · ${a.date}<div class="small">${activitySummary(a)||'Keine Messwerte eingetragen'}</div><div class="row"><button class="pill" onclick="editAct('${a.id}')">Bearbeiten</button><button class="pill" onclick="delAct('${a.id}')">Löschen</button></div></div>`).join(''):'<div class="empty">Noch keine Aktivitäten.</div>'}</div>`}
function sportPage(){let a=editing?db.activities.find(x=>x.id===editing):null;if(a)current=a.sport;let sport=SPORTS.find(s=>s[0]===current)||SPORTS[0],ms=db.metrics.filter(m=>m.sports.includes(current));return `<div class="top"><div class="brand">${sport[1]}</div>${icon(current)}</div><form class="panel stack" onsubmit="saveAct(event)"><h2>${a?'Aktivität bearbeiten':'Neue Aktivität'}</h2><p class="small">Alle Angaben sind optional und können später geändert oder gelöscht werden.</p><label>Datum<input name="date" type="date" value="${a?.date||new Date().toISOString().slice(0,10)}"></label>${ms.map(m=>`<label>${esc(m.name)}${m.unit?' ('+esc(m.unit)+')':''}<input name="m_${m.id}" type="${m.type==='number'?'number':'text'}" step="any" value="${esc(a?.values?.[m.id]??'')}"></label>`).join('')}<button class="btn">${a?'Änderungen speichern':'Speichern'}</button>${a?`<button type="button" class="btn alt" onclick="cancelEdit()">Abbrechen</button>`:''}</form>`}
function settings(){return `<div class="brand">Setup</div><section class="panel"><h2>Datenfelder</h2><p class="small">Die eingebauten Felder sind Vorschläge. Kein Feld ist verpflichtend. Du kannst Namen, Einheit und Zuordnung jederzeit ändern.</p>${db.metrics.map(m=>`<div class="metric"><span><b>${esc(m.name)}</b> ${esc(m.unit||'')}<br><span class="small">${m.sports.map(k=>SPORTS.find(s=>s[0]===k)?.[1]).join(', ')}</span></span><button class="pill" onclick="editMetric('${m.id}')">Ändern</button>${m.standard?'':`<button class="pill" onclick="delMetric('${m.id}')">×</button>`}</div>`).join('')}<h3>Eigenes Feld</h3><form class="stack" onsubmit="addMetric(event)"><input name="name" placeholder="z. B. Temperatur" required><input name="unit" placeholder="Einheit"><select name="type"><option value="number">Zahl</option><option value="text">Text</option></select><div class="checks">${SPORTS.map(s=>`<label class="check"><input type="checkbox" name="sports" value="${s[0]}">${s[1]}</label>`).join('')}</div><button class="btn">Datenfeld anlegen</button></form></section><section class="panel"><h2>Sicherung</h2><div class="row"><button class="btn" onclick="exportData()">Alles exportieren</button><button class="btn alt" onclick="document.querySelector('#importFile').click()">Importieren</button></div></section>`}
function chartPage(){let numeric=db.metrics.filter(m=>m.type==='number');let presets=[['Umfang: Dauer',['duration']],['Distanz',['distance']],['Herzfrequenz',['heart']],['Belastung',['effort']],['Watt + Herzfrequenz',['power','heart']],['Distanz + Dauer',['distance','duration']]];return `<div class="brand">Auswertung</div><section class="panel stack"><h2>Sinnvolle Diagramme</h2><div class="row">${presets.map((p,i)=>`<button class="pill" onclick='preset(${JSON.stringify(p[1])})'>${p[0]}</button>`).join('')}</div><h2>Eigene Verschneidung</h2><p class="small">Alle vorhandenen numerischen Werte können kombiniert und als Favorit gespeichert werden.</p><div class="checks">${numeric.map(m=>`<label class="check"><input class="series" type="checkbox" value="${m.id}" onchange="drawChart()">${esc(m.name)}</label>`).join('')}</div><canvas id="chart" width="700" height="360"></canvas><div class="row"><input id="favName" placeholder="Name des Favoriten" style="flex:1"><button class="btn" onclick="saveFav()">Favorit speichern</button></div></section><section class="panel"><h2>Favoriten</h2>${db.favorites.map(f=>`<div class="metric"><button class="pill" onclick="loadFav('${f.id}')">${esc(f.name)}</button><button class="pill" onclick="delFav('${f.id}')">×</button></div>`).join('')||'<div class="small">Noch keine Favoriten.</div>'}</section>`}
function go(v){editing=null;view=v;render()}function openSport(k){current=k;editing=null;view='sport';render()}function newEntry(){current='walking';editing=null;view='sport';render()}
function saveAct(e){e.preventDefault();let f=new FormData(e.target),values={};db.metrics.filter(m=>m.sports.includes(current)).forEach(m=>{let v=f.get('m_'+m.id);if(v!=='')values[m.id]=m.type==='number'?Number(v):v});let date=f.get('date')||new Date().toISOString().slice(0,10);if(editing){let a=db.activities.find(x=>x.id===editing);a.sport=current;a.date=date;a.values=values}else db.activities.push({id:crypto.randomUUID(),sport:current,date,values});editing=null;save();view='data';render()}
function editAct(id){editing=id;view='sport';render()}function cancelEdit(){editing=null;view='data';render()}function delAct(id){if(confirm('Aktivität löschen?')){db.activities=db.activities.filter(a=>a.id!==id);save();render()}}
function addMetric(e){e.preventDefault();let f=new FormData(e.target),sports=f.getAll('sports');if(!sports.length)return alert('Bitte mindestens eine Sportart wählen.');db.metrics.push({id:crypto.randomUUID(),name:f.get('name'),unit:f.get('unit'),type:f.get('type'),sports,standard:false});save();render()}
function editMetric(id){let m=db.metrics.find(x=>x.id===id);let name=prompt('Name des Datenfelds:',m.name);if(name===null)return;let unit=prompt('Einheit:',m.unit||'');if(unit===null)return;let choices=SPORTS.map((s,i)=>`${i+1}=${s[1]}`).join(', ');let initial=m.sports.map(k=>SPORTS.findIndex(s=>s[0]===k)+1).join(',');let raw=prompt(`Sportarten als Nummern, durch Komma getrennt:\n${choices}`,initial);if(raw===null)return;let sports=[...new Set(raw.split(',').map(x=>SPORTS[Number(x.trim())-1]?.[0]).filter(Boolean))];if(!sports.length)return alert('Mindestens eine Sportart wählen.');m.name=name.trim()||m.name;m.unit=unit.trim();m.sports=sports;save();render()}
function delMetric(id){if(!confirm('Eigenes Datenfeld löschen?'))return;db.metrics=db.metrics.filter(m=>m.id!==id);save();render()}
function selected(){return [...document.querySelectorAll('.series:checked')].map(x=>x.value)}function preset(ids){document.querySelectorAll('.series').forEach(x=>x.checked=ids.includes(x.value));drawChart()}
function drawChart(){let c=document.querySelector('#chart');if(!c)return;let ctx=c.getContext('2d'),ids=selected();ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle='#bbb';ctx.beginPath();ctx.moveTo(50,20);ctx.lineTo(50,320);ctx.lineTo(680,320);ctx.stroke();let rows=db.activities.filter(a=>ids.some(id=>a.values?.[id]!==undefined)).sort((a,b)=>a.date.localeCompare(b.date));if(!ids.length||!rows.length){ctx.fillStyle='#666';ctx.font='18px Arial';ctx.fillText(ids.length?'Noch keine passenden Daten':'Datenreihen auswählen',220,180);return}let marks=['#111','#19a8d8','#6dcc73','#ff812b','#8a5bd6','#d43c74'];ids.forEach((id,j)=>{let values=rows.map(a=>Number(a.values?.[id])).filter(Number.isFinite),min=Math.min(...values),max=Math.max(...values);if(min===max){min-=1;max+=1}ctx.strokeStyle=marks[j%marks.length];ctx.lineWidth=4;ctx.beginPath();let started=false;rows.forEach((a,i)=>{let v=Number(a.values?.[id]);if(!Number.isFinite(v))return;let x=50+(rows.length===1?315:i*630/(rows.length-1)),y=320-(v-min)*280/(max-min);started?ctx.lineTo(x,y):(ctx.moveTo(x,y),started=true)});ctx.stroke();ctx.fillStyle=marks[j%marks.length];ctx.fillRect(55,25+j*22,14,4);ctx.fillStyle='#111';ctx.font='14px Arial';ctx.fillText(db.metrics.find(m=>m.id===id)?.name||'',75,32+j*22)});ctx.fillStyle='#555';ctx.font='12px Arial';ctx.fillText(rows[0].date,50,342);ctx.fillText(rows.at(-1).date,600,342)}
function saveFav(){let ids=selected(),name=document.querySelector('#favName').value.trim();if(!ids.length||!name)return alert('Bitte Datenreihen wählen und einen Namen eingeben.');db.favorites.push({id:crypto.randomUUID(),name,metricIds:ids});save();render()}function loadFav(id){let f=db.favorites.find(x=>x.id===id);document.querySelectorAll('.series').forEach(x=>x.checked=f.metricIds.includes(x.value));drawChart()}function delFav(id){db.favorites=db.favorites.filter(f=>f.id!==id);save();render()}
function exportData(){let blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mein-sport-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
document.querySelector('#importFile').addEventListener('change',async e=>{let f=e.target.files[0];if(!f)return;try{let x=JSON.parse(await f.text());if(!x.metrics||!x.activities||!x.favorites)throw 0;if(confirm('Import ersetzt alle aktuellen Daten. Fortfahren?')){db=x;ensureDefaults();save();render()}}catch{alert('Ungültige Backup-Datei.')}e.target.value=''})
function isStandalone(){return window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true}
async function installApp(){
 if(isStandalone())return alert('Du verwendest Mein Sport bereits als installierte App.');
 if(deferredInstallPrompt){deferredInstallPrompt.prompt();let choice=await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;updateInstallButton();if(choice.outcome!=='accepted')return;return}
 alert('Android/Chrome meldet diese PWA bereits als installiert oder bietet den Installationsdialog gerade nicht an. Öffne sie über das App-Symbol auf deinem Startbildschirm. Falls du sie neu installieren möchtest, deinstalliere zuerst die vorhandene Mein-Sport-App und lade diese Seite anschließend neu.');
}
function updateInstallButton(){let b=document.querySelector('#installBtn');if(!b)return;b.textContent=isStandalone()?'App ist installiert':(deferredInstallPrompt?'App installieren':'App öffnen / installieren')}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;updateInstallButton()});
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;updateInstallButton()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();updateInstallButton();
